### PR TITLE
Delegated source file search to find linux system call

### PR DESCRIPTION
**Pull request by alimovlex**
Hello!
I have automated your test script using find posix utility.

### CODE REVIEW

**Comment by jvalcher** [comment]
Thanks for the PR! 

As they are now, I feel like these changes add unnecessary complexity. However, I would be willing to consider automation like this if it allowed future developers to easily add different source code files and builds. Off the top of my head it would need to accomplish the following:

- All source code files put into their own folder called `test_files`

- Divide the compiler commands by filetype into nested lists (right now there is only one per filetype)

```
c_commands = [ 
    [ 'gcc', '-Wall', ... ], 
    [ 'gcc', '-Werror', ... ], 
    ... 
]
cpp_commands = [ 
    ... , 
    ... 
]
```

- Run each command on each file of that type, with each build clearly labeled
```

File:  <filename>
Command:  <command> 

```
If this isn't something you're willing to do, let me know, and I'll just turn it into an issue.

**Comment by alimovlex** [comment]
> Thanks for the PR!
> 
> As they are now, I feel like these changes add unnecessary complexity. However, I would be willing to consider automation like this if it allowed future developers to easily add different source code files and builds. Off the top of my head it would need to accomplish the following:
> 
> * All source code files put into their own folder called `test_files`
> * Divide the compiler commands by filetype into nested lists (right now there is only one per filetype)
> 
> ```
> c_commands = [ 
>     [ 'gcc', '-Wall', ... ], 
>     [ 'gcc', '-Werror', ... ], 
>     ... 
> ]
> cpp_commands = [ 
>     ... , 
>     ... 
> ]
> ```
> 
> * Run each command on each file of that type, with each build clearly labeled
> 
> ```
> 
> File:  <filename>
> Command:  <command> 
> ```
> 
> If this isn't something you're willing to do, let me know, and I'll just turn it into an issue.

I made the makefile for these purposes that automates the process of building the source code.

**Comment by alimovlex** [comment]
It is done. The makefile has been completed.

**Comment by jvalcher** [comment]
This doesn't address the issue that I discussed. Using a makefile with all those variables instead of a Python script adds even more complexity IMO. Sorry but I'm closing this PR, as it does not solve an existing problem or improve testing.

**Comment by alimovlex** [comment]
> This doesn't address the issue that I discussed. Using a makefile with all those variables instead of a Python script adds even more complexity IMO. Sorry but I'm closing this PR, as it does not solve an existing problem or improve testing.

Well, I am not the python coder. If you have a better vision, I'll be glad to see what are you doing with your repository.

**Pull request closed without merging**
